// <auto-generated />
using System;
using CategoryMicroservice.Api.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CategoryMicroservice.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CategoryMicroservice.Api.Models.Business.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ReviewsCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8697d5b5-e2a4-4ed8-9723-81d981ca4d51"),
                            Name = "Техника",
                            ReviewsCount = 0
                        },
                        new
                        {
                            Id = new Guid("dee670bb-90d0-443a-b77f-347e85e59cec"),
                            Name = "Авто",
                            ReviewsCount = 0
                        },
                        new
                        {
                            Id = new Guid("431b57c0-315f-42a7-b699-647af7843273"),
                            Name = "Красота и здоровье",
                            ReviewsCount = 0
                        },
                        new
                        {
                            Id = new Guid("15c2d4a7-9dac-44b7-acb9-f493ccdfc99d"),
                            Name = "Детское",
                            ReviewsCount = 0
                        },
                        new
                        {
                            Id = new Guid("a4953008-2fc2-4ed2-9ab8-302bdd2f9e69"),
                            Name = "Разное",
                            ReviewsCount = 0
                        });
                });

            modelBuilder.Entity("CategoryMicroservice.Api.Models.Business.Subcategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ReviewsCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Subcategories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3f76067a-fa50-44f4-99cd-d10bc32d5387"),
                            CategoryId = new Guid("8697d5b5-e2a4-4ed8-9723-81d981ca4d51"),
                            Name = "Для дома",
                            ReviewsCount = 0
                        },
                        new
                        {
                            Id = new Guid("769fcc5d-4a3a-4436-86a7-3dfbb9bf3de0"),
                            CategoryId = new Guid("8697d5b5-e2a4-4ed8-9723-81d981ca4d51"),
                            Name = "Компьютеры",
                            ReviewsCount = 0
                        },
                        new
                        {
                            Id = new Guid("e53a33f9-f947-4d75-8aa9-b29a5e926f20"),
                            CategoryId = new Guid("8697d5b5-e2a4-4ed8-9723-81d981ca4d51"),
                            Name = "Аксессуары для техники",
                            ReviewsCount = 0
                        },
                        new
                        {
                            Id = new Guid("d5d44835-e8d8-44c5-8035-80d2b6ff8ca1"),
                            CategoryId = new Guid("8697d5b5-e2a4-4ed8-9723-81d981ca4d51"),
                            Name = "Техника - разное",
                            ReviewsCount = 0
                        },
                        new
                        {
                            Id = new Guid("45ba3685-954e-4ee8-b9e5-c26101c1cc08"),
                            CategoryId = new Guid("dee670bb-90d0-443a-b77f-347e85e59cec"),
                            Name = "Автомобили",
                            ReviewsCount = 0
                        },
                        new
                        {
                            Id = new Guid("0dda864d-96de-482a-85e7-693611dc211c"),
                            CategoryId = new Guid("dee670bb-90d0-443a-b77f-347e85e59cec"),
                            Name = "Запчасти",
                            ReviewsCount = 0
                        },
                        new
                        {
                            Id = new Guid("c59369e4-9f1c-4265-8100-0477c14640d1"),
                            CategoryId = new Guid("dee670bb-90d0-443a-b77f-347e85e59cec"),
                            Name = "Авто - разное",
                            ReviewsCount = 0
                        },
                        new
                        {
                            Id = new Guid("dfb3cedf-63aa-4004-bfc1-eaec31d3467c"),
                            CategoryId = new Guid("431b57c0-315f-42a7-b699-647af7843273"),
                            Name = "Ухаживающая косметика",
                            ReviewsCount = 0
                        },
                        new
                        {
                            Id = new Guid("63114816-16bf-43fd-bfa4-c0434959b23c"),
                            CategoryId = new Guid("431b57c0-315f-42a7-b699-647af7843273"),
                            Name = "Косметические аксессуары",
                            ReviewsCount = 0
                        },
                        new
                        {
                            Id = new Guid("9b49d48c-3024-4194-8b51-638fea13f64f"),
                            CategoryId = new Guid("431b57c0-315f-42a7-b699-647af7843273"),
                            Name = "Похудение",
                            ReviewsCount = 0
                        },
                        new
                        {
                            Id = new Guid("72cea28b-9495-41e2-878f-1f1a58d25a43"),
                            CategoryId = new Guid("431b57c0-315f-42a7-b699-647af7843273"),
                            Name = "Спорт/фитнес-клубы",
                            ReviewsCount = 0
                        },
                        new
                        {
                            Id = new Guid("76fab645-53b0-4714-8243-a8e3dbad8500"),
                            CategoryId = new Guid("431b57c0-315f-42a7-b699-647af7843273"),
                            Name = "Товары для здоровья",
                            ReviewsCount = 0
                        },
                        new
                        {
                            Id = new Guid("485d0a5a-4361-41c4-a22c-71ffb0aabfc6"),
                            CategoryId = new Guid("431b57c0-315f-42a7-b699-647af7843273"),
                            Name = "Спортивные товары",
                            ReviewsCount = 0
                        },
                        new
                        {
                            Id = new Guid("7c3c149a-d162-4e64-9b9b-ca62066387fb"),
                            CategoryId = new Guid("431b57c0-315f-42a7-b699-647af7843273"),
                            Name = "Красота, здоровье - разное",
                            ReviewsCount = 0
                        },
                        new
                        {
                            Id = new Guid("a30799d9-653a-4181-8592-1c468634b788"),
                            CategoryId = new Guid("15c2d4a7-9dac-44b7-acb9-f493ccdfc99d"),
                            Name = "Одежда для девочек",
                            ReviewsCount = 0
                        },
                        new
                        {
                            Id = new Guid("426327e2-9ca1-489c-8adb-098a4cf3ddac"),
                            CategoryId = new Guid("15c2d4a7-9dac-44b7-acb9-f493ccdfc99d"),
                            Name = "Одежда для мальчиков",
                            ReviewsCount = 0
                        },
                        new
                        {
                            Id = new Guid("2f6d561b-072d-405d-ae1c-2312dbdc6f19"),
                            CategoryId = new Guid("15c2d4a7-9dac-44b7-acb9-f493ccdfc99d"),
                            Name = "Детская обувь",
                            ReviewsCount = 0
                        },
                        new
                        {
                            Id = new Guid("181ddb8a-f92c-4518-abe2-b514e354df81"),
                            CategoryId = new Guid("15c2d4a7-9dac-44b7-acb9-f493ccdfc99d"),
                            Name = "Детские игрушки",
                            ReviewsCount = 0
                        },
                        new
                        {
                            Id = new Guid("adea119a-4d4b-4358-b4e7-25c4146a7a24"),
                            CategoryId = new Guid("15c2d4a7-9dac-44b7-acb9-f493ccdfc99d"),
                            Name = "Детское - разное",
                            ReviewsCount = 0
                        },
                        new
                        {
                            Id = new Guid("9470f494-f597-4f6f-b1ec-0391afeff754"),
                            CategoryId = new Guid("a4953008-2fc2-4ed2-9ab8-302bdd2f9e69"),
                            Name = "Одежда",
                            ReviewsCount = 0
                        },
                        new
                        {
                            Id = new Guid("6dcad3c5-0b4e-4c56-b603-a9c1544798b7"),
                            CategoryId = new Guid("a4953008-2fc2-4ed2-9ab8-302bdd2f9e69"),
                            Name = "Обувь",
                            ReviewsCount = 0
                        },
                        new
                        {
                            Id = new Guid("2aabcf86-3ccf-4382-ad2a-dc996353f3a8"),
                            CategoryId = new Guid("a4953008-2fc2-4ed2-9ab8-302bdd2f9e69"),
                            Name = "Ремонт",
                            ReviewsCount = 0
                        },
                        new
                        {
                            Id = new Guid("cb45da5e-bc7b-4687-bba8-8ea0f637210c"),
                            CategoryId = new Guid("a4953008-2fc2-4ed2-9ab8-302bdd2f9e69"),
                            Name = "Компьютерные игры",
                            ReviewsCount = 0
                        },
                        new
                        {
                            Id = new Guid("d6453ea4-5f00-4df3-9eb0-2baafe26aaf8"),
                            CategoryId = new Guid("a4953008-2fc2-4ed2-9ab8-302bdd2f9e69"),
                            Name = "Другое",
                            ReviewsCount = 0
                        });
                });

            modelBuilder.Entity("CategoryMicroservice.Api.Models.Business.Subcategory", b =>
                {
                    b.HasOne("CategoryMicroservice.Api.Models.Business.Category", null)
                        .WithMany("Subcategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CategoryMicroservice.Api.Models.Business.Category", b =>
                {
                    b.Navigation("Subcategories");
                });
#pragma warning restore 612, 618
        }
    }
}
